name: Run Arbitrary Node Code
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    name: Run Node Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Update source code
        run: npm start

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Jordan Bachmann
          author_email: jordan.bachmann@gmail.com
          message: "Updated index.html"
          add: "index.html"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
